# Page settings

baseurl = "https://parkietje.github.io/resume/"
#baseurl = "/resume"
languageCode = "en-us"
title = "parkietje CV"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Yanni Chiodi CV"
    author = "parkietje"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Yanni Chiodi"
        tagline = "Computer Science student"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: yannichiodi@gmail.com"
        title = "yannichiodi@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+31636311670"
        title = "+31636311670"

        # [[params.contact.list]]
        # class = "website"
        # icon = "fa-globe"
        # url = "//portfoliosite.com"
        # title = "portfoliosite.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "https://www.linkedin.com/in/yanni-chiodi-153ba9165/"
        title = "linkedin.com/yannichiodi"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/Parkietje"
        title = "github.com/Parkietje"

        # [[params.contact.list]]
        # class = "twitter"
        # icon = "fa-twitter"
        # url = "//twitter.com/username"
        # title = "@twittername"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "MSc. Computer Science"
        college = "Delft University of Technology"
        dates = "2018 - present"

        [[params.education.list]]
        degree = "BSc. Aerospace Engineering"
        college = "Delft University of Technology"
        dates = "2012 - 2017"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Dutch"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Fluent"

        [[params.language.list]]
        language = "French"
        level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Skateboarding"

        [[params.interests.list]]
        interest = "Surfing"

        [[params.interests.list]]
        interest = "Chess"
        url = "lichess.org"

        [[params.interests.list]]
        interest = "Magic: the gathering"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Intro"
        summary = "I am an ambitious computer science student, looking for professional experience as a developer. I am socially outgoing and like to work in teams on complex projects. My professional interests are **back-end development, distributed systems** and **cybersecurity**"

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Work Experience"

        [[params.jobs.list]]
        position = "QA Engineer"
        dates = "September 2018 - Present"
        company = "Nielsen Media Analytics, Rotterdam"
        details = "Quality Assurance engineer for sophisticated media analytics tool with distributed architecture. My responsibilities include: UI testing, API testing, and performance/load testing using Jmeter. My involvement in QA has led to well over a hundred bugfixes, and increased awareness about the state of performance of our software within the team."

        [[params.jobs.list]]
        position = "Administrative Assistant"
        dates = "July 2016 - August 2016"
        company = "Uniforwarding NV, Antwerp"
        details = "I provided a solution to the bottleneck that came from manually processing data across spreadsheets. I used Visual Basic for documents generation (invoices, receipts, loading lists, ...), and delivered an Excel tool which was well received by the company."

        # [[params.jobs.list]]
        # position = "UI Developer"
        # dates = "2012 - 2014"
        # company = "Amazon, London"
        # details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

        # Projects section
        [params.projects]
            enable = true
            icon = "fa-archive"
            title = "Projects"

            [[params.projects.list]]
            title = "Personal page"
            url = "https://parkietje.github.io/webpage/"
            tagline = "A personal webpage deployed to Github Pages."

            [[params.projects.list]]
            title = "Crypto trading bot"
            url = "https://gekko.wizb.it"
            tagline = "I used Gekko, an open source tool, to implement and backtest cryptocurrency trading strategies."

            # [[params.projects.list]]
            # title = "dropdelft"
            # url = "https://www.dropdelft.nl"
            # tagline = "I am one of the maintainers of my student association website"



    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Java"
        level = "80%"

        [[params.skills.list]]
        skill = "Python, SQL"
        level = "55%"

        [[params.skills.list]]
        skill = "Golang"
        level = "50%"

        [[params.skills.list]]
        skill = "Jmeter, Postman"
        level = "45%"

        [[params.skills.list]]
        skill = "React, node.js"
        level = "40%"

        [[params.skills.list]]
        skill = "Flutter, Android (java)"
        level = "35%"

        [[params.skills.list]]
        skill = "docker"
        level = "30%"

        [[params.skills.list]]
        skill = "AWS, Google Cloud"
        level = "30%"

        [[params.skills.list]]
        skill = "html, css"
        level = "15%"
